### PR TITLE
Creating A Demo

### PR DESCRIPTION
**Pull request by kengoon**
demo supports:

- [x] share file
- [x] share text
- [x] app restart
- [x] download manager
- [x] change status bar color
- [x] change navigation bar color
- [x] set wallpaper
- [x] text to speech
- [x] immersive mode
- [x] launch app
- [x] get app details
- [x] play local music
- [x] stream online music
- [x] make call
- [x] dial call
- [x] read contact
- [x] open chrome custom tab webview
- [x] send notification

### CODE REVIEW

**Comment by kengoon** [comment]
@yunus-ceyhan please test the apk, download it from here https://mega.nz/file/CUQnhAJZ#TpHr4MYmcO9EMo-3XTZLcJjVDbCe237sRfoi5g2vDt8

PS: `set_wallpaper` malfunctions, you might want to use `logcat` to see the error

**Comment by yunus-ceyhan** [comment]
> @yunus-ceyhan please test the apk, download it from here https://mega.nz/file/CUQnhAJZ#TpHr4MYmcO9EMo-3XTZLcJjVDbCe237sRfoi5g2vDt8
> 
> PS: `set_wallpaper` malfunctions, you might want to use `logcat` to see the error

Unfortunatelly my device rejected to install it, says that's a trojan virus . I'm always installing debugded apks, haven't seen such a warning before. What might you have used in the application that could cause this error?

@kengoon

**Comment by kengoon** [comment]
@yunus-ceyhan I include all the permission, I guess that is the reason

**Comment by yunus-ceyhan** [comment]
Then you may need to request for only required permission.

**Comment by kengoon** [comment]
Yea, I would do that

**Comment by kengoon** [comment]
@yunus-ceyhan here https://mega.nz/file/CYRi3RyI#AvQovSNhyWNL4cd1bVrJTxgMCZq94bl8xHA05lINF0U is the new apk with only the required permission

**Comment by yunus-ceyhan** [comment]
@kengoon 

set_wallpper crash because it needs SET_WALLPAPER permission.
`must have permission android.permission.SET_WALLPAPER java.lang.SecurityException`

launch_app externally is not working either. I guess that's your addaption, so what's difference between launch internally and externally?

```
platform/build-armeabi-v7a/build/python-installs/kvdroid/armeabi-v7a/kvdroid/tools/__init__.py", line 219, in launch_app_externally
01-05 22:59:38.950 26711 26734 I python  :    File "jnius/jnius_export_class.pxi", line 1145, in jnius.jnius.JavaMultipleMethod.__call__
01-05 22:59:38.951 26711 26734 I python  :    File "jnius/jnius_export_class.pxi", line 857, in jnius.jnius.JavaMethod.__call__
01-05 22:59:38.951 26711 26734 I python  :    File "jnius/jnius_export_class.pxi", line 954, in jnius.jnius.JavaMethod.call_method
01-05 22:59:38.951 26711 26734 I python  :    File "jnius/jnius_utils.pxi", line 91, in jnius.jnius.check_exception
01-05 22:59:38.952 26711 26734 I python  :  jnius.jnius.JavaException: JVM exception occurred: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference java.lang.NullPointerException
01-05 22:59:38.952 26711 26734 I python  : Python for android ended.
```

**Comment by kengoon** [comment]
@yunus-ceyhan via the launch_exernally and launch_internally i didn't launch a specifc activity, i only launched the Main app itself. 
I will fix that

via set wallpapaer, i will set that too

**Comment by kengoon** [comment]
@yunus-ceyhan I might delay on this PR for a while. I am experimenting on new features which might be included on the demo

**Comment by yunus-ceyhan** [comment]
> @yunus-ceyhan I might delay on this PR for a while. I am experimenting on new features which might be included on the demo

No worries,  we don't have a time limit.

**Comment by kengoon** [comment]
@yunus-ceyhan test this https://mega.nz/file/OYwS2SZb#oCpE4rDpJpUpmTIylxR91n5LtNY3dBh6DWRr8aPgZy8 out, if it looks good, then I think this PR should be merged

**Comment by yunus-ceyhan** [comment]
> @yunus-ceyhan test this https://mega.nz/file/OYwS2SZb#oCpE4rDpJpUpmTIylxR91n5LtNY3dBh6DWRr8aPgZy8 out, if it looks good, then I think this PR should be merged

Send notification is not working on Android 12. App crashes immediately while trying to create. Here are the logs.

```
03-13 10:52:36.943  1195  1343 I python  :  jnius.jnius.JavaException: JVM exception occurred: org.android.kvdroid: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
03-13 10:52:36.943  1195  1343 I python  :  Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles. java.lang.IllegalArgumentException
03-13 10:52:36.943  1195  1343 I python  : Python for android ended.`
```

**Comment by kengoon** [comment]
> > @yunus-ceyhan test this https://mega.nz/file/OYwS2SZb#oCpE4rDpJpUpmTIylxR91n5LtNY3dBh6DWRr8aPgZy8 out, if it looks good, then I think this PR should be merged
> 
> Send notification is not working on Android 12. App crashes immediately while trying to create. Here are the logs.
> 
> ```
> 03-13 10:52:36.943  1195  1343 I python  :  jnius.jnius.JavaException: JVM exception occurred: org.android.kvdroid: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
> 03-13 10:52:36.943  1195  1343 I python  :  Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles. java.lang.IllegalArgumentException
> 03-13 10:52:36.943  1195  1343 I python  : Python for android ended.`
> ```

I will see to that immediately

**Comment by kengoon** [comment]
@yunus-ceyhan check this https://mega.nz/file/DEAnySAa#EuwD4VEfaidYosQA0IjSqOWwzo72chwUGAT3cK96sRM

**Comment by yunus-ceyhan** [comment]
Making notification is not working on Android 12, the app crashes immediately, I'll look into logcat to find out why.
Pazar, 13 Mart 2022, 00:22ÖÖ +03:00 gönderen: Akubue-Izundu Kenechukwu  ***@***.*** :

***@***.*** test this  https://mega.nz/file/OYwS2SZb#oCpE4rDpJpUpmTIylxR91n5LtNY3dBh6DWRr8aPgZy8 out, if it looks good, then I think this PR should be merged

**Comment by kengoon** [comment]
@yunus-ceyhan I thought this has already been fixed on the last commit relating to this PR

**Comment by yunus-ceyhan** [comment]
What the hell is going on. I didn't write that message, how could it be possible? I need to change my password immediately..

**Comment by yunus-ceyhan** [comment]
I'm 100 percent sure I didn't post anything on GitHub 4 days ago and I still couldn't get how that happened.

**Comment by kengoon** [comment]
Alright

**Pull request merged**
